### ISSUE TITLE
Issue with Slice Function, included point not being evaluated correctly when checking pmf

### ISSUE THREAD

**Issue by toast682** [vincenzocoia/distplyr#19]
``` r
library(distplyr)
library(testthat)
d1 <- dst_norm(0, 1)
d2 <- dst_empirical(0:4)
d <- mix(d1, d2)
dl_not <- slice_left(d, 0, include = FALSE)
dr_not <- slice_right(d, 0, include = FALSE)
expect_equal(eval_pmf(dl_not, at = 0, strict = FALSE), 0.1)
#> Error: eval_pmf(dl_not, at = 0, strict = FALSE) not equal to 0.1.
#> 1/1 mismatches
#> [1] 0 - 0.1 == -0.1
expect_equal(eval_pmf(dr_not, at = 0, strict = FALSE), 1 / 6)
#> Error: eval_pmf(dr_not, at = 0, strict = FALSE) not equal to 1/6.
#> 1/1 mismatches
#> [1] 0 - 0.167 == -0.167
```

**Comment by toast682** [comment]
Eval_pmf is evaluating to zero, when the answer should be 1.2. 
``` r
library(distplyr)
library(testthat)
d1 <- dst_norm(0, 1)
d3 <- dst_empirical(1:5)
m2 <- mix(d1, d3, weights = c(0.4, 0.6))
expect_identical(
    eval_pmf(m2, at = c(0.5, 1, 1.5), strict = FALSE),
    c(0, 0.2 * 0.6, 0)
  )
#> Error: eval_pmf(m2, at = c(0.5, 1, 1.5), strict = FALSE) not identical to c(0, 0.2 * 0.6, 0).
#> 1/3 mismatches
#> [2] 0 - 0.12 == -0.12
```

<sup>Created on 2021-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincenzocoia** [comment]
@yelselmiao The error in the second comment has been fixed. The first comment need some attention:

- The 0.1 and 1/6 in the `expect_equal()` call may not be correct. What should the pmf evaluate to? And, do the `eval_pmf` functions actually evaluate to those quantities?

Another issue is with `prob_left()`. This function is like a cdf, but allows you to either use `<` or `<=`. Please take a look to ensure it's defined properly. (We are thinking: the if statement should be `!inclusive`, and should _subtract_ the pmf, not add it.). Can you take a look at `prob_right()` as well?

**Comment by vincenzocoia** [comment]
Solved!
